# CMake generated Testfile for 
# Source directory: /home/runner/work/bolt-cppml/bolt-cppml/test
# Build directory: /home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(basic_bolt_test "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_basic_test")
set_tests_properties(basic_bolt_test PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;47;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_all_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests")
set_tests_properties(bolt_all_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;161;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_chat_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "Chat")
set_tests_properties(bolt_chat_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;162;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_memory_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "MemoryManager")
set_tests_properties(bolt_memory_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;163;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_store_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "ChatStore")
set_tests_properties(bolt_store_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;164;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_string_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "StringUtils")
set_tests_properties(bolt_string_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;165;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_file_tree_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "FileTree")
set_tests_properties(bolt_file_tree_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;166;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_minimap_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "Minimap")
set_tests_properties(bolt_minimap_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;167;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_split_view_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_split_view_tests")
set_tests_properties(bolt_split_view_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;168;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_multi_cursor_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_multi_cursor_tests")
set_tests_properties(bolt_multi_cursor_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;169;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_keyboard_shortcuts_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_keyboard_shortcuts_tests")
set_tests_properties(bolt_keyboard_shortcuts_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;170;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_theme_system_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_theme_system_tests")
set_tests_properties(bolt_theme_system_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;171;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_plugin_system_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_plugin_system_tests")
set_tests_properties(bolt_plugin_system_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;172;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_error_handling_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "ErrorHandling")
set_tests_properties(bolt_error_handling_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;174;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_memory_error_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "MemoryManagerErrors")
set_tests_properties(bolt_memory_error_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;175;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_message_error_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "MessageHandlerErrors")
set_tests_properties(bolt_message_error_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;176;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_store_error_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "ChatStoreErrors")
set_tests_properties(bolt_store_error_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;177;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_editor_error_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "EditorStoreErrors")
set_tests_properties(bolt_editor_error_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;178;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_workbench_error_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "WorkbenchStoreErrors")
set_tests_properties(bolt_workbench_error_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;179;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_error_recovery_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "ErrorRecovery")
set_tests_properties(bolt_error_recovery_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;180;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_ggml_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "GGMLTest")
set_tests_properties(bolt_ggml_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;181;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_ai_models_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "AIModels")
set_tests_properties(bolt_ai_models_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;182;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_debugger_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "Debugger")
set_tests_properties(bolt_debugger_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;183;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_logging_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_unit_tests" "Logging")
set_tests_properties(bolt_logging_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;184;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_collaboration_tests "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_collaboration_tests")
set_tests_properties(bolt_collaboration_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;185;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_integration_all "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_integration_tests")
set_tests_properties(bolt_integration_all PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;187;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
add_test(bolt_integration_basic "/home/runner/work/bolt-cppml/bolt-cppml/build-coverage/test/bolt_integration_tests" "Integration")
set_tests_properties(bolt_integration_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;188;add_test;/home/runner/work/bolt-cppml/bolt-cppml/test/CMakeLists.txt;0;")
